create table if not exists public.script_reviews (
  id bigint generated by default as identity primary key,
  title text not null,
  script_text text not null,
  highlights text not null default '[]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.script_reviews enable row level security;
