-- Supabase Dashboard > SQL Editor에서 한 번 실행할 초기 스키마입니다.
-- 온라인 버전으로 전환하기 전까지 현재 로컬 앱은 이 테이블을 사용하지 않습니다.

create table if not exists public.settings (key text primary key, value text not null);

create table if not exists public.practices (
  id bigint generated by default as identity primary key,
  practice_date date not null,
  activity_type text not null check (activity_type in ('simultaneous','consecutive','sight_translation','shadowing')),
  direction text not null check (direction in ('KO→JA','JA→KO')),
  title text not null, topic text default '', source_url text default '', video_speed double precision not null default 1.0,
  minutes integer not null check (minutes > 0),
  difficulty integer not null check (difficulty between 1 and 5),
  omission integer not null default 0, number_omission integer not null default 0,
  logic_error integer not null default 0, expression_block integer not null default 0,
  unnatural_expression integer not null default 0, other_notes text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.language_pairs (
  id bigint generated by default as identity primary key,
  korean text not null, japanese text not null,
  pair_type text not null check (pair_type in ('collocation','term','pattern','other')),
  source text default '', notes text default '',
  mastery integer not null default 1 check (mastery between 1 and 5),
  created_at timestamptz not null default now(), last_reviewed_at timestamptz,
  review_count integer not null default 0, review_score double precision not null default 0
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  pair_id bigint not null references public.language_pairs(id) on delete cascade,
  rating integer not null check (rating in (0,1,2)),
  reviewed_at timestamptz not null default now()
);

create table if not exists public.study_notes (
  id bigint generated by default as identity primary key,
  note_date date not null, title text not null, content text not null, tags text default '',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

insert into public.settings(key,value) values
  ('exam_date','2026-12-01'), ('weekly_ko_ja_goal','70'),
  ('weekly_ja_ko_goal','70'), ('weekly_pairs_goal','40')
on conflict (key) do nothing;

alter table public.settings enable row level security;
alter table public.practices enable row level security;
alter table public.language_pairs enable row level security;
alter table public.reviews enable row level security;
alter table public.study_notes enable row level security;

create table if not exists public.script_feedbacks (
  id bigint generated by default as identity primary key,
  feedback_date date not null,
  interpretation_type text not null check (interpretation_type in ('동시통역','순차통역')),
  direction text not null check (direction in ('KO→JA','JA→KO')),
  title text not null, source_script text not null, interpreted_script text not null,
  feedback text not null, created_at timestamptz not null default now()
);
alter table public.script_feedbacks enable row level security;

create table if not exists public.script_reviews (
  id bigint generated by default as identity primary key,
  title text not null, script_text text not null, highlights text not null default '[]',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.script_reviews enable row level security;

create table if not exists public.sight_translation_events (
  id bigint generated by default as identity primary key,
  practice_date date not null default current_date,
  direction text not null check (direction in ('KO→JA','JA→KO')),
  created_at timestamptz not null default now()
);
alter table public.sight_translation_events enable row level security;

-- 보안을 위해 공개 접근 정책은 만들지 않습니다.
-- 다음 단계에서 로그인 또는 서버 전용 연결 방식을 정한 뒤 정책을 추가합니다.
