-- 기존 Supabase 프로젝트에서 SQL Editor로 한 번 실행하세요.
alter table public.practices add column if not exists video_speed double precision not null default 1.0;

create table if not exists public.script_feedbacks (
  id bigint generated by default as identity primary key,
  feedback_date date not null,
  interpretation_type text not null check (interpretation_type in ('동시통역','순차통역')),
  direction text not null check (direction in ('KO→JA','JA→KO')),
  title text not null,
  source_script text not null,
  interpreted_script text not null,
  feedback text not null,
  created_at timestamptz not null default now()
);

alter table public.script_feedbacks enable row level security;
