create table if not exists public.sight_translation_events (
  id bigint generated by default as identity primary key,
  practice_date date not null default current_date,
  direction text not null check (direction in ('KO→JA','JA→KO')),
  created_at timestamptz not null default now()
);
alter table public.sight_translation_events enable row level security;
