-- 공부 자료 게시판 테이블 추가: Supabase SQL Editor에서 한 번 실행하세요.
create table if not exists public.study_materials (
  id bigint generated by default as identity primary key,
  title text not null,
  content_html text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.study_materials enable row level security;
